### ISSUE TITLE
Published version is outdated

### ISSUE THREAD

**Issue by jonaskuske** [NotTheDr01ds/WSLTabCompletion#3]
Hi, the current version `0.8.0` that is published in the PowerShell Gallery does not include the fix for `-t` that was merged in March. (https://github.com/NotTheDr01ds/WSLTabCompletion/pull/2)
Please release a `0.8.1` :)

**Comment by NotTheDr01ds** [comment]
@jonaskuske So sorry - I pulled that in, but it needed (needs) quite a few updates to bring it in line with the latest WSL releases, and I never got around to doing that.  Yes, I should have gone ahead and released.  Brushing it off at the moment and should have some updates soon.

**Comment by NotTheDr01ds** [comment]
I feel like with 0.8.3 it's at least no longer outdated.  Not done-done, but I *think* I have basic completion for all of the recent commands in there.

Let me know if you spot any issues, though.
